default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5433

development:
  <<: *default
  database: todo_api_development

test:
  <<: *default
  database: todo_api_test

production:
  <<: *default
  database: todo_api_production
  username: todo_api
  password: <%= ENV['TODO_API_DATABASE_PASSWORD'] %>
  port: 5432