# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62cb39557bf0012d659915827696c5311678d856c4b3e830af03528101e8d89ccc68c57be98941ec7299a9d410586791885911e9865ad5f15fb968407191d363

test:
  secret_key_base: dcf5cd4a0aa0d218d07160e09b6064db56066b66bd1a252124dcbcc638d1e2a06938393b3a9adcf38c680fad86a65a382bc613b2f5eb3b16e06f1d18ac433b6d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
